name:                cap20
version:             0.1.0.0
github:              "petrem/cap20"
license:             BSD3
author:              "Petre Mierluțiu"
maintainer:          "petrem@github"
copyright:           "Public Domain"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/petrem/cap20#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - QuickCheck
    - checkers

executables:
  cap20-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cap20

tests:
  cap20-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cap20
    - hspec
    - QuickCheck
    - checkers
    - hspec-checkers
