name:                wordnumber
version:             0.1.0.0
github:              "petrem/wordnumber"
license:             BSD3
author:              "Petre Mierluțiu"
maintainer:          "petrem@github"
copyright:           "Public Domain"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/petrem/wordnumber#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules: WordNumber

tests:
  wordnumber-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wordnumber
    - hspec
    - QuickCheck
